[[provider]]
provider = "github"
name = "orf"
path = "github"
env_var = "GITHUB_TOKEN"
skip_forks = false

[[provider]]
provider = "gitlab"
name = "tom6"
url = "https://gitlab.com"
path = "gitlab"
env_var = "GITLAB_TOKEN"
