on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Run bootstrap
        shell: bash
        run: |
          ./bootstrap.sh
        env:
          REPO: ${{github.workspace}}
          SKIP_MAS: 1