on: [push]

name: CI

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Run bootstrap
        shell: bash
        run: |
          brew untap caskroom/versions
          ./bootstrap.sh
        env:
          REPO: ${{github.workspace}}
          DOTFILES_REF: ${{github.sha}}
          SKIP_MAS: 1
          HOMEBREW_BUNDLE_BREW_SKIP: "node"
